#!/usr/bin/env python3
"""Converts a PNG icon into OledBitmap data (see src/oled_gfx.h).

Usage:
    python3 tools/png_to_oled.py assets/oled_frames/bell.png
        -> writes src/oled_icon_bell.h, containing `oledIconBell`

    python3 tools/png_to_oled.py bell.png wifi.png
        -> converts each one separately (one header per PNG)

    python3 tools/png_to_oled.py --out src/oled_frames_config.h a.png b.png c.png
        -> combines several PNGs into a single header instead (opt-in;
           useful for a set of frames that get cycled together)

A pixel counts as "on" (lit, bit=1) if it's dark; black is ON, white is
OFF, matching how these get drawn on the panel (dark background, bright
foreground) even though the source PNGs are exported as black-on-white for
easy editing/preview.

Height should ideally be a multiple of 8 (one page); if it isn't, the
image is padded with blank (OFF) rows on the bottom up to the next
multiple of 8 rather than failing. Width has no such constraint — it's
drawn one pixel-column at a time, so any width works as-is.

Writes a `static const uint8_t <name>_data[] PROGMEM` byte array plus a
`static const OledBitmap <name>` wrapping it, in the page-major layout
oledDrawBitmap() expects. Regenerate this way any time the source PNG
changes rather than hand-editing the header.
"""
import argparse
import re
import sys
from pathlib import Path

from PIL import Image

LUMINANCE_ON_THRESHOLD = 128  # 0-255; darker than this counts as "on"


def name_from_filename(path):
    stem = Path(path).stem
    words = re.split(r"[^A-Za-z0-9]+", stem)
    camel = "".join(w[:1].upper() + w[1:] for w in words if w)
    return "oledIcon" + camel


def convert(path):
    im = Image.open(path).convert("RGB")
    w, h = im.size

    # Width is free — oledWritePage() addresses columns one pixel at a
    # time, so any width works. Height is the one that has to land on a
    # page boundary (8px), since each byte packs 8 vertical pixels.
    padded_h = (h + 7) // 8 * 8
    if padded_h != h:
        print(f"{path}: height {h} isn't a multiple of 8 — padding to {padded_h} (blank on the bottom)")
        canvas = Image.new("RGB", (w, padded_h), (255, 255, 255))  # white = OFF
        canvas.paste(im, (0, 0))
        im = canvas
        h = padded_h

    px = im.load()
    pages = h // 8
    data = bytearray()
    for page in range(pages):
        for x in range(w):
            byte = 0
            for bit in range(8):
                y = page * 8 + bit
                r, g, b = px[x, y]
                luminance = (r + g + b) / 3
                if luminance < LUMINANCE_ON_THRESHOLD:
                    byte |= 1 << bit
            data.append(byte)
    return w, pages, data


def emit_array(out, name, data):
    out.write(f"static const uint8_t {name}_data[] PROGMEM = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    out.write("};\n")


def write_header(out_path, entries):
    """entries: list of (name, source_png_path)."""
    with open(out_path, "w") as out:
        out.write("#pragma once\n\n")
        out.write("#include <Arduino.h> // for PROGMEM\n")
        out.write("#include <stdint.h>\n\n")
        out.write('#include "oled_gfx.h"\n\n')
        out.write(f"// Generated by tools/png_to_oled.py from {', '.join(p for _, p in entries)}.\n")
        out.write("// Do not hand-edit — change the source PNG and regenerate instead.\n\n")

        for name, path in entries:
            w, pages, data = convert(path)
            emit_array(out, name, data)
            out.write(f"static const OledBitmap {name} = {{{w}, {pages}, {name}_data}};\n\n")
            print(f"{path}: {w}x{pages * 8} -> {name} ({len(data)} bytes)")

    print(f"wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("pngs", nargs="+", help="one or more PNG files to convert")
    parser.add_argument("--out", help="combine all PNGs into this one header instead of one-per-PNG")
    args = parser.parse_args()

    if args.out:
        entries = [(name_from_filename(p), p) for p in args.pngs]
        write_header(args.out, entries)
    else:
        for p in args.pngs:
            name = name_from_filename(p)
            out_path = Path("src") / f"oled_icon_{Path(p).stem}.h"
            write_header(out_path, [(name, p)])


if __name__ == "__main__":
    main()
